[general]
import = [
  "~/.config/alacritty/themes/doom-one.toml",
  "~/.config/alacritty/fonts/jetbrains.toml",
]

[cursor]
thickness = 0.2
# smooth_motion = false
# smooth_motion_factor = 0.8
# smooth_motion_spring = 0.5
# smooth_motion_max_stretch_x = 3.0
# smooth_motion_max_stretch_y = 3.0

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[terminal]
shell = "/bin/bash"

[window]
opacity = 0.8
title = "Alacritty"

[window.padding]
x = 10
y = 10

